server:
  port: 12386

spring:
  application:
    name: ts-execute-service
swagger:
  controllerPackage: execute.controller

opentracing:
  jaeger:
    udp-sender:
      host: ${NODE_IP:jaeger}
      port: 6831