server:
  port: 18767

spring:
  application:
    name: ts-admin-basic-info-service

swagger:
  controllerPackage: adminbasic.microservice

opentracing:
  jaeger:
    udp-sender:
      host: ${NODE_IP:jaeger}
      port: 6831