server:
  port: 18898

spring:
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller

opentracing:
  jaeger:
    udp-sender:
      host: ${NODE_IP:jaeger}
      port: 6831