server:
  port: 16113

spring:
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller

opentracing:
  jaeger:
    udp-sender:
      host: ${NODE_IP:jaeger}
      port: 6831