# HTTP Server
server:
  port: 14322  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-plan-service


swagger:
  controllerPackage: travelplan.controller

opentracing:
  jaeger:
    udp-sender:
      host: ${NODE_IP:jaeger}
      port: 6831