spring:
  application:
    name: ts-security-service
  data:
    mongodb:
      host: ts-security-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 11188  # HTTP (Tomcat) port

swagger:
  controllerPackage: security.controller

opentracing:
  jaeger:
    udp-sender:
      host: ${NODE_IP:jaeger}
      port: 6831