spring:
  application:
    name: ts-route-plan-service

# HTTP Server
server:
  port: 14578 # HTTP (Tomcat) port


swagger:
  controllerPackage: plan.controller

opentracing:
  jaeger:
    udp-sender:
      host: ${NODE_IP:jaeger}
      port: 6831